[build-system]
requires = ["setuptools>=75", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "smartmeter"
version = "0.0.3"
description = "Smartmeter package for reading and parsing p1 data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyserial>=3.5",
]

[project.scripts]
read_p1 = "smartmeter.cli.read_p1:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["smartmeter*"]
namespaces = true

[tool.setuptools_scm]


[tool.pytest.ini_options]
pythonpath = [
  "src/"
]
minversion = "8.0"
testpaths = ["tests/"]
addopts = [
    "--import-mode=importlib",
]

[tool.coverage.run]
branch = true
relative_files = false

[tool.uv]
prerelease = "allow"
link-mode = "copy"
cache-keys = [{ git = { commit = true, tags = true } }]

[dependency-groups]
dev = [
    "coverage>=7.6.10",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.9",
    "tox>=4.24.1",
    "tox-uv>=1.25.0",
]

[tool.ruff]
line-length = 79
indent-width = 4
extend-exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist"
]

[tool.ruff.lint]
extend-select = ["B", "Q"]
extend-ignore = ["E203"]

[tool.ruff.lint.pycodestyle]
max-line-length = 79
