[tox]
requires =
    tox>=4
    tox-uv
env_list =
    clean
    formatting
    linters
    coverage
    coverage_report

[testenv]
runner = uv-venv-lock-runner
allowlist_externals =
    coverage
    pytest
    ruff

[testenv:formatting]
description = run code formatter checking via ruff
skip_install = true
deps =
    ruff
commands =
    ruff format --config {toxinidir}/pyproject.toml --check {toxinidir}/src

[testenv:linters]
description = run linters via ruff check
skip_install = true
deps =
    ruff
commands =
    ruff check --config {toxinidir}/pyproject.toml {toxinidir}/src

[testenv:clean]
deps = coverage
skip_install = True
commands = coverage erase

[testenv:coverage]
description = PyTest with Coverage
depends = clean
skip_install = False
allowlist_externals =
    python
setenv =
    CI = true
    coverage_report_xml={env:coverage_report_xml:{toxinidir}/coverage-reports/coverage.xml}
    junit_xml={env:junit_xml:{toxinidir}/TEST-pytest-junit.xml}
commands =
    pytest  \
    --junitxml={env:junit_xml} \
    --cov={toxinidir}/src \
    --cov-report=xml:{env:coverage_report_xml} \
    {toxinidir}/tests

[testenv:coverage_report]
description = Create the coverage reports
depends = coverage
deps = coverage
skip_install = True
commands =
    coverage report

#[coverage:paths]
#source =
#    src/
#
#[coverage:run]
#relative_files = True
#source = src/
#branch = True
#
